### ISSUE TITLE
Related Tables Need to be Accessible from Popup

### ISSUE THREAD

**Issue by marshallrobinson** [UGS-GIO/boreholeApp#12]
The related tables (sample and unit table) in the current data service need to be accessible in a way that makes sense. Preferably as links to a textual borehole description (graphic would be nice, but that is more work) within each borehole's popup

Let's all chat specifics when @lance-weaver can start working on this feature.

**Comment by lance-weaver** [comment]
Check out what I've got done, and give some details on what related table info you need and how you want it displayed.

**Comment by marshallrobinson** [comment]
@lance-weaver is working on updating the formatting of the data panel.

**Comment by marshallrobinson** [comment]
I'm going through old issues. Has this been taken care of? I think it has, but wanted to confirm.
