### ISSUE TITLE
Current Database Has Duplicates

### ISSUE THREAD

**Issue by ericksonugs** [UGS-GIO/boreholeApp#13]
When going through a statistical analysis of the spreadsheet I found 81 borehole, 203 unit, and 333 sample duplicates, due to source reports being duplicates. I removed the duplicates from the Primary 2019-2020 spreadsheet. This is a low priority and can be resolved on the next updated with the 2020-2021 spreadsheet data.

**Comment by marthajensen** [comment]
@ericksonugs please have a look at the app. The new data should be there now

**Comment by ericksonugs** [comment]
Everything looks good, this issue has been resolved.
