### ISSUE TITLE
Some Bore Locations are Incorrect

### ISSUE THREAD

**Issue by ericksonugs** [UGS-GIO/boreholeApp#17]
The following Bore_IDs had incorrect coordinates. The source spreadsheet has been corrected, the geodatabase needs to be updated with the corrected locations of only these Bore_IDs:

40-8S-3E-7F_U1
40-8S-3E-7F_U2
40-8S-3E-7F_W3
40-8S-3E-7F_U6
40-8S-3E-7F_U7
40-8S-3E-7F_U8

**Comment by marthajensen** [comment]
The corrected points have been added to the ArcGIS Server service...

**Comment by ericksonugs** [comment]
The Bore_IDs are confirmed to be in the correct locations, thanks @marthajensen.
