### ISSUE TITLE
Database Update January 2021

### ISSUE THREAD

**Issue by ericksonugs** [UGS-GIO/boreholeApp#18]
The spreadsheets for the database have been updated with 260 more subsurface explorations. The new data is available to be appended to the current database from the Google Share UGS_Hazards_Geotech\Subsurface WebApp Database file SubsurfaceDatabase_UPDATE_01-2021.xlsx 

The file SubsurfaceDatabase_CurrentDatabase.xlsx also contains the update and all other data.

**Comment by gordondouglass** [comment]
I have updated the borehole database with new data that Ben provided:
There are now 3819 borehole locations. I have put a copy of the database here:
G:\Shared drives\UGS_Hazards_Geotech\Geotechnical Database
And it is called:
Borehole_Data_20210115.gdb
It contains the borehole locations as well as the related tables.
I have also updated the AGOL interactive web web map to reflect the new data set:
https://utahdnr.maps.arcgis.com/home/webmap/viewer.html?webmap=2b71bcef49ef4ec8ab33fee092caeb65

**Comment by ericksonugs** [comment]
Thanks for updating!

**Comment by marthajensen** [comment]
I'm going to reopen this. I haven't added the new data to the web app yet

**Comment by marthajensen** [comment]
@marshallrobinson the new data has been added. Please check.  The data points tagged with 1/5/2021 @ 5 pm are new. 

![image](https://user-images.githubusercontent.com/11522897/105722905-6335f600-5ee3-11eb-84fb-9d4da65678fd.png)

**Comment by ericksonugs** [comment]
Confirmed, the update has been applied, thanks @marthajensen!

**Comment by ericksonugs** [comment]
Closing as a new update is ready https://github.com/UGS-GIO/boreholeApp/issues/25
