### ISSUE TITLE
Search Returns No Results

### ISSUE THREAD

**Issue by ericksonugs** [UGS-GIO/boreholeApp#20]
When searching, no results are found. Entering the example borehole id (041734_TH-1), or a lat/long (40.38255600, -111.86641100, comma or space separated) brings no results. Tried searching with Chrome and Firefox browsers with the same outcome of no results.

**Comment by lance-weaver** [comment]
@ericksonugs  Fixed.  It was searching the objectid field.   Now it searches "boreid", "project_name", "projectid" fields.  If you'd like others, let me know.

However, it can only do ONE display field (the field that show's up in the suggestion drop down).   Right now, I have boreid showing there, but you'll need to let me know what you'd prefer.

**Comment by ericksonugs** [comment]
I think we should go with the BoreID for the suggestion dropdown. The project ID are part of the BoreID and the project name will be too large for the suggestion pull down, as many will have the same first few words ie: "Geotechnical Investigation of," or something similar.

**Comment by ericksonugs** [comment]
Related to the search, when you go to the resulting location and the popup box has "Show More Results" and a list is revealed when clicking showing similar results. The issue is when you are zoomed into the location and click another result the box disappears and you remain at the original location. If you zoom out you will see a new box at the location you clicked for the other result. We should either have the map zoom out to reveal the clicked location or zoom to the clicked location.

**Comment by marshallrobinson** [comment]
@ericksonugs Check out the search functionality again and let us know what you think.

**Comment by ericksonugs** [comment]
I checked the search function and project ID and Borehole suggestions come up, looks great! However, I still remain in the same location when searching and when zoomed in, out of the frame of the results, I have no indication of the results. Example: search for 1070587_BH1 with all points on the map, click on the "zoom to" in the result box option, a couple times, where you zoom in close to the point. Then maintaining that zoom level, search for 0605-022-13_B-1, you will not know where that exploration is or what the results are unless you zoom out to where the point gets in frame. We should either have the map zoom out and re-frame to all the points be visible or move to the results location, maintaining the same zoom level.

**Comment by marshallrobinson** [comment]
@lance-weaver maybe the autoNavigate property can be set to true instead of false? I don't know if that will affect the zoom level when you do a new search, but that should pan the user to the location of the search result.

**Comment by lance-weaver** [comment]
I enabled auto navigate to search results, check it out and see if this functionality is what your're looking for.

**Comment by ericksonugs** [comment]
@lance-weaver the auto navigate works, thanks!
