### ISSUE TITLE
Legend

### ISSUE THREAD

**Issue by marshallrobinson** [UGS-GIO/boreholeApp#21]
Change "Exploration_Method" to "Exploration Method".

Not sure if @marthajensen or @lance-weaver has better control over this...

**Comment by marthajensen** [comment]
I tried to change this in the map legend and republish but I don't have control over it. @lance-weaver can you change it?

**Comment by lance-weaver** [comment]
I think its pretty easy for me to fix it.  Let me make a legend definition.

**Comment by marshallrobinson** [comment]
I was able to fix this by changing the exploration_method field's alias to "Exploration Method"
