### ISSUE TITLE
Mike Review

### ISSUE THREAD

**Issue by marshallrobinson** [UGS-GIO/boreholeApp#26]
This application is ready for your review when you have time. 
Let me know if you have any questions. 
The link is: https://geology.utah.gov/apps/borehole.

**Comment by mikehylland** [comment]
1. The database/map name should be revised. "Subsurface Geologic Database" suggests the user will have access to all kinds of subsurface data, including deep (i.e., oil and gas) well data, perhaps data from underground mines, etc. The data here appear to be limited to relatively shallow explorations of a geotechnical nature (and that's the impression one gets from the "About" window). Would something like "Shallow Subsurface Geologic Database" or "Subsurface Geotechnical Database" work?

2. In the "About" window, please use "data" in the plural sense (several instances).

3. "Legend" window: Seems like the heading "Geologic Boreholes" should be deleted. The next heading, "Exploration Method," is what's being explained (although "Exploration Type" would be more accurate), and the exploration types include trenches (i.e., types other than boreholes).

4. "Layers" window: Recommend a different name for the "Geologic Boreholes" layer. Again, the map shows data associated with things other than boreholes. 

5. In the "Get Sample Data" windows, sections are labeled "Borehole Project Details," "Borehole Unit Data," and "Borehole Sampling Data" even when the exploration was a trench or test pit (i.e., not a borehole). Why not simply delete "Borehole" from these and just use Project Details, Unit Data, and Sampling Data so they universally apply to any exploration type?

**Comment by ericksonugs** [comment]
> 1. The database/map name should be revised. "Subsurface Geologic Database" suggests the user will have access to all kinds of subsurface data, including deep (i.e., oil and gas) well data, perhaps data from underground mines, etc. The data here appear to be limited to relatively shallow explorations of a geotechnical nature (and that's the impression one gets from the "About" window). Would something like "Shallow Subsurface Geologic Database" or "Subsurface Geotechnical Database" work?

Yes, it is too general for the map. Let's rename it to Subsurface Geotechnical Database. Based on the 3D meeting yesterday, it will eventually be rolled into an all-inclusive subsurface webmap, best to distinguish the type now.

> 2. In the "About" window, please use "data" in the plural sense (several instances).

Can you elaborate? I added you as an editor to the reviewed document for this entry. https://docs.google.com/document/d/1JF1mOvV-FlcM8q5VVjv3sEHe2gG-KPKN1ykrwuRMuRE/edit?usp=sharing

> 3. "Legend" window: Seems like the heading "Geologic Boreholes" should be deleted. The next heading, "Exploration Method," is what's being explained (although "Exploration Type" would be more accurate), and the exploration types include trenches (i.e., types other than boreholes).

Yes, it should be Exploration Method, if the upper heading is needed, use Geotechnical Explorations. Our spreadsheet for data entry has ExplorationType (borehole, test hole, test pit, cpt, etc.) with very few trenches, and ExplorationMethod should only have three options: Excavation, Drill, or Cone Penetration Test (CPT). The method is what needs to be defined here. There are very few CPT and would ideally be placed the lowest in the legend.

> 4. "Layers" window: Recommend a different name for the "Geologic Boreholes" layer. Again, the map shows data associated with things other than boreholes.

Yes, it should be Geotechnical Explorations. Considering the eventual 3D map, we should use Geotechnical Explorations to distinguish it from other geologic explorations.

> 5. In the "Get Sample Data" windows, sections are labeled "Borehole Project Details," "Borehole Unit Data," and "Borehole Sampling Data" even when the exploration was a trench or test pit (i.e., not a borehole). Why not simply delete "Borehole" from these and just use Project Details, Unit Data, and Sampling Data so they universally apply to any exploration type?

 Yes, eliminating Borehole is best for the data section. We should also change the "Get Sample Data" to "Get Geotechnical Data."

**Comment by ericksonugs** [comment]
@mikehylland comments have been updated in the About document and are now available for access. https://docs.google.com/document/d/1JF1mOvV-FlcM8q5VVjv3sEHe2gG-KPKN1ykrwuRMuRE/edit?usp=sharing
