### ISSUE TITLE
This Application Needs New Data Added to Borehole

### ISSUE THREAD

**Issue by ericksonugs** [UGS-GIO/boreholeApp#27]
### Name of Existing Layer (as it appears in the application)

Borehole Explorations

### Folder path of data

G:\Shared drives\UGS_Hazards_Geotech\Subsurface WebApp Database

### Why do you feel this application needs what you're requesting?

I updated the spreadsheet with current data. There were some edits to previous entries, a database refresh is needed. 

SubsurfaceDatabase_CurrentDatabase.xlsx

### Who has reviewed your database so far (e.g. Schema, Field Types, Topology, etc.)?

I reviewed data from geotech entries and volunteers 

### Who has reviewed your science and grammar so far?

none

**Comment by marthajensen** [comment]
@CyndiAndersen @gordondouglass

**Comment by marthajensen** [comment]
@CyndiAndersen 

Where are we at on this?

**Comment by marthajensen** [comment]
@ericksonugs 
I am sending you a geodatabase for review (created via the script we talked about). Once you give me the okay, we can upload the new data

**Comment by marthajensen** [comment]
@ericksonugs 

actually instead of sending it via email, I am uploading the zipped gdb here to github. If the data looks good (or bad) let me know. 
[borehole_app_scripted.gdb.zip](https://github.com/UGS-GIO/boreholeApp/files/8904248/borehole_app_scripted.gdb.zip)

**Comment by ericksonugs** [comment]
> @ericksonugs
> 
> actually instead of sending it via email, I am uploading the zipped gdb here to github. If the data looks good (or bad) let me know. [borehole_app_scripted.gdb.zip](https://github.com/UGS-GIO/boreholeApp/files/8904248/borehole_app_scripted.gdb.zip)

Reviewed and looks good. Another update will be submitted for the final update for this fiscal year.

**Comment by marthajensen** [comment]
@ericksonugs 

Thank you for reviewing the data. Do you think the final fiscal year update will be ready within the next week or two? If so, I  think I might wait and push up all the new data at once. If the time frame is longer, I'll probably serve this data up soon. What's your timeline?

**Comment by ericksonugs** [comment]
Yes, I'm planning to have it ready and submitted to you this week. I'll create a new issue for that update.
