### ISSUE TITLE
This Application Needs New Data Added to Borehole

### ISSUE THREAD

**Issue by ericksonugs** [UGS-GIO/boreholeApp#28]
### Name of Existing Layer (as it appears in the application)

Borehole Explorations

### Folder path of data

G:\Shared drives\UGS_Hazards_Geotech\Subsurface WebApp Database\SubsurfaceDatabase_CurrentDatabase.xlsx

### Why do you feel this application needs what you're requesting?

To close out the fiscal year, this is the final update for FY 2021-2022. The file is the complete database with corrections made to previous entries. Please replace the existing database with this current one.

### Who has reviewed your database so far (e.g. Schema, Field Types, Topology, etc.)?

Elizabeth Williams and Ben Erickson

### Who has reviewed your science and grammar so far?

Ben Erickson

**Comment by ericksonugs** [comment]
Can I get an ETA for this update?

**Comment by marthajensen** [comment]
Hey Ben - sorry. Somehow this issue slipped through the cracks. I thought that we had been waiting on a new dataset and it looks like this was the dataset we were waiting for :). I'll get to this ASAP

**Comment by ericksonugs** [comment]
Great, thanks!

**Comment by marthajensen** [comment]
@ericksonugs 

Hey Ben - the new data is in the app. Please check it when you have time. Thanks!

**Comment by ericksonugs** [comment]
Reviewed, and everything looks good. Thanks!
