### ISSUE TITLE
This Application Needs New Data Added to Borehole Explorations

### ISSUE THREAD

**Issue by ericksonugs** [UGS-GIO/boreholeApp#29]
### Name of Existing Layer (as it appears in the application)

Borehole Explorations

### Folder path of data

G:\Shared drives\UGS_Hazards_Geotech\Subsurface WebApp Database\SubsurfaceDatabase_CurrentDatabase.xlsx

### Why do you feel this application needs what you're requesting?

The 2022-2023 fiscal year closing brings an update to the database. The referenced Excel spreadsheet has been appended with the new data. Let @ericksonugs know if the format needs to be changed or if there are any questions. 

### Who has reviewed your database so far (e.g. Schema, Field Types, Topology, etc.)?

Ben Erickson, Stormie Elmer

### Who has reviewed your science and grammar so far?

Ben Erickson

**Comment by nmpayne** [comment]
Awesome I will let know you know if I have any questions. Thanks!

**Comment by nmpayne** [comment]
The data on the web app and on the sde has been updated.

**Comment by ericksonugs** [comment]
I confirmed that the updated data is visible on the web portal. Thanks!
