### ISSUE TITLE
This Application Needs New Data Added to [name of layer]

### ISSUE THREAD

**Issue by ericksonugs** [UGS-GIO/boreholeApp#30]
### Name of Existing Layer (as it appears in the application)

Borehole Explorations

### Folder path of data

G:\Shared drives\UGS_Hazards_Geotech\Subsurface WebApp Database\SubsurfaceDatabase_CurrentDatabase.xlsx

### Why do you feel this application needs what you're requesting?

The referenced Excel spreadsheet has been appended with the new data. Let @ericksonugs know if there are any questions.

### Who has reviewed your database so far (e.g. Schema, Field Types, Topology, etc.)?

Ben Erickson, Stormie Elmer

### Who has reviewed your science and grammar so far?

Ben Erickson

**Comment by marshallrobinson** [comment]
Thanks, this has been put in the queue and Nate will let you know an approximate timeline and if there are questions.

**Comment by marshallrobinson** [comment]
@nmpayne 
Make sure this gets published before May 1, 2024. Please let me know if you have any questions.

**Comment by nmpayne** [comment]
The new date is on the app.

**Comment by ericksonugs** [comment]
Confirmed, the app reflects the new data from this update
