### ISSUE TITLE
Report URL is incorrectly referenced. 

### ISSUE THREAD

**Issue by ericksonugs** [UGS-GIO/boreholeApp#31]
### What happened?

1. Access any exploration's detail.
2. Click the _External Link_ adjacent to Report URL:
3. The link opens the referenced exploration's report, but there is an added decimal (.0) to UGS_GDID value (ie: https://geodata.geology.utah.gov/pages/view.php?ref=71650.0). 

### What did you expect to happen?

This value should be an integer, having a decimal value may cause issues with the archive reference. 

### Browser Version

Any

**Comment by marshallrobinson** [comment]
Thanks for finding that and letting us know. Strange that it adds the ".0". I've confirmed that it does show up that way in the database as well. 

@nmpayne will you please remove the .0 from each report_url entry?

**Comment by nmpayne** [comment]
This was fixed with the new data update.

**Comment by ericksonugs** [comment]
Confirmed .0 addition has been removed in the external link link
