### ISSUE TITLE
FY '21 Hours

### ISSUE THREAD

**Issue by marshallrobinson** [UGS-GIO/boreholeApp#9]
@pyroclast77, for the purpose of budgeting, approximately how many hours (if any) are written into grants for web services in FY '21 for this project? Grant's USGS project is asking for hundreds of hours and I want to make sure you get the amount of time you need for this project as well.

Thanks!

**Comment by pyroclast77** [comment]
Steve has been managing that aspect of the project, he should have those figures.

**Comment by marshallrobinson** [comment]
@sdbowman, for the purpose of budgeting, approximately how many hours (if any) are written into grants for web services in FY '21 for this project (please let me know if you have other grant-funded projects for web services here as well)? Grant's USGS project is asking for hundreds of hours and I want to make sure you get the amount of time you need for this project as well.

Thanks!

**Comment by sdbowman** [comment]
We do not have any hours budgeted for web services, except that in UGP2
(FY2020 Geologic Data Preservation Project) that is part of the Energy and
Minerals Program part of the project.  However, we do need to complete the
borehole app (Utah Subsurface 3D Database) project.
Thanks, Steve.

Steve D. Bowman,  Ph.D., P.E., P.G.
Geologic Hazards Program Manager
Utah Geological Survey
1594 West North Temple, P.O. Box 146100
Salt Lake City, Utah 84114-6100
(801) 537-3304
https://geology.utah.gov/
